version: "3.9"

services:
  outline:
    environment:
      URL: http://${DOCS_DOMAIN}
      FORCE_HTTPS: "false"
      FILE_STORAGE: s3
      AWS_S3_UPLOAD_BUCKET_URL: http://minio:9000
      AWS_S3_FORCE_PATH_STYLE: "true"
  n8n:
    environment:
      N8N_PROTOCOL: http
      WEBHOOK_URL: http://${FLOW_DOMAIN}/
  nginx:
    environment:
      ENABLE_TLS: "false"
  certbot:
    profiles: ["prod"]

  minio-setup:
    image: minio/mc:latest
    depends_on:
      - minio
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minioadmin}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minioadmin}
      AWS_S3_UPLOAD_BUCKET_NAME: ${AWS_S3_UPLOAD_BUCKET_NAME}
    entrypoint: ["sh", "-lc"]
    command: |
      "mc alias set local http://minio:9000 $MINIO_ROOT_USER $MINIO_ROOT_PASSWORD && \
       mc mb --ignore-existing local/$AWS_S3_UPLOAD_BUCKET_NAME"
